### ISSUE TITLE
Realización del Plugin Cardify - Nataly/JessicaMeza

### ISSUE THREAD

**Issue by jessica2011** [NatalyOC/cardify#5]
- [x] Formar equipo.
- [x] Elegir reto.
- [x] Hacer fork de reto modelo o crear nuevo repo si has propuesto un reto no propuesto por Laboratoria.
- [x] Escribir primera versión del README.md con una descripción general de la librería así como ejemplos (snippets) de uso y configuración (si fuera necesario).
- [x] Crear issues y milestones que sirvan como hoja de ruta (roadmap)
Inicializar proyecto con npm init y git init.
- [x] Crear index.html con ejemplo principal de uso.

**Comment by NatalyOC** [comment]
Se sube a rama plugins-noteroc el index con ejemplo principal de uso

**Comment by NatalyOC** [comment]
se agrego primera version del readme
